version: '3'
services:
  db:
    image: postgres:9.6.15-alpine
    container_name: db
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./data:/var/lib/postgresql/data
  cache:
    image: redis:latest
    container_name: cache
    ports:
      - 6379:6379
