version: '3'
services:
  db:
    image: postgres:9.6.15-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
  redis:
    image: redis:latest
    ports:
      - 6379:6379
